version: '3.8'
services:
  app:
    build:
      context: .
    container_name: E-learning-nodejs-app
    ports:
      - 8000:8000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    # depends_on:
    #   - db
  # db:
  #   container_name: elearning-postgres
  #   image: postgres
  #   restart: always
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: elearning_database
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin@admin.com
    ports:
      - '5050:80'
networks:
  nodejs-exa:
    driver: bridge
