version: '3.8'
services:
  app:
    build:
      context: .
    container_name: E-learning-nodejs-app
    ports:
      - 8000:8000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    networks:
      - nodejs-exa
  app2:
    build:
      context: .
    container_name: E-learning-nodejs-app2
    ports:
      - 8002:8000
    volumes:
      - .:/usr/src/app
    networks:
      - nodejs-exa
    # depends_on:
    #   - db
  # db:
  #   container_name: elearning-postgres
  #   image: postgres
  #   restart: always
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: elearning_database
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: elearning-redis
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    networks:
      - nodejs-exa
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - app
        - app2
      networks:
        - nodejs-exa
networks:
  nodejs-exa:
    driver: bridge
volumes:  # Add a volumes section to define named volumes
  data-redis:  # Define the named volume
