openapi: 3.0.0
info:
  description: |
    API Document for Movie Website
  version: '1.0.0'
  title: PBL6-Movie Website API
  contact:
    email: phucchp@gmail.com
servers:
  - url: 'http://localhost:8000/api'
tags:
  - name: authentication
    description: API for Authentication
  - name: course
    description: API for Courses
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /courses:
    get:
      tags:
        - course
      summary: Get all courses or by filter
      description: Get and search courses API
      parameters:
        - name: search
          in: query
          description: Enter value to search by title and discription of courses
          required: false
          explode: true
          schema:
            type: string
        - name: duration
          in: query
          description: Filter by total durations of courses 
          required: false
          style: form
          explode: true  # Do not explode the array
          schema:
            type: array
            items:
              type: string
              enum:
                - extraShort
                - short
                - medium
                - long
                - extraLong
        - name: price
          in: query
          description: Filter by price of courses (free or paid)
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - free
                - paid
        - name: category
          in: query
          description: Filter by category courses, enter categoryId of Category
          required: false
          explode: true
          schema:
            type: string
        - name: averageRating
          in: query
          description: Filter by average rating course, enter average rating of course to filter
          required: false
          explode: true
          schema:
            type: number
        - name: languageId
          in: query
          description: Filter by language of course
          required: false
          explode: true
          schema:
            type: number
        - name: level
          in: query
          description: Choose level to filter
          required: false
          explode: true
          schema:
            type: array
            items:
              type: number
              enum:
                - 1
                - 2
                - 3
        - name: sort
          in: query
          description: Choose addition to sort
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - price
                - discount
                - duration
                - averageRating
                - totalStudents
                - createdAt
        - name: sortBy
          in: query
          description: Default sort ASC, if you want change to DESC, select below
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - ASC
                - DESC
              default: ASC
        - name: page
          in: query
          description: Use to pagination, default page = 1
          required: false
          explode: true
          schema:
            type: number
        - name: pageSize
          in: query
          description: Use to pagination, default pageSize = 10
          required: false
          explode: true
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
        '400':
          description: Can not get courses